# Generated by Django 2.1.4 on 2018-12-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
